# + -------------------------------------------------------------------------------- + #
# | DATABASE SETTINGS ( 데이터베이스 설정 )
# | 해당 플러그인은 데이터베이스를 필수로 연결합니다.
# + -------------------------------------------------------------------------------- + #
database:
  host: localhost
  port: 3306
  database: ragina
  username: root
  password: Sunny439501!


# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# + -------------------------------------------------------------------------------- + #
messages:
  # (메시지 앞에 붙는) 접두사
  prefix: ' &6접속보상 | &r'

  # 콘피그를 리로드 하였을 때 출력되는 메시지
  reloadComplete: '&a콘피그를 리로드하였습니다.'


errorMessages:
  # 권한이 없을 때 출력되는 메시지
  notAnOperator: '&c해당 명령어를 실행할 권한이 없습니다.'

  # 콘솔에서 불가능 명령어를 사용하였을 때 출력되는 메시지
  noConsoleCommand: '&c콘솔에서는 불가능한 명령어입니다. (인게임에서 시도해주세요)'

  # 잘못된 명령어를 사용하였을 때 출력되는 메시지
  wrongCommand: '&c잘못된 명령어입니다. (다시 시도해주세요)'