# + -------------------------------------------------------------------------------- + #
# | DATABASE SETTINGS ( 데이터베이스 설정 )
# | 해당 플러그인은 데이터베이스를 필수로 연결합니다.
# + -------------------------------------------------------------------------------- + #
database:
  host: localhost
  port: 3306
  database: regina
  username: root
  password: password1234!@#$


# + -------------------------------------------------------------------------------- + #
# | REWARD SETTINGS ( 보상 설정 )
# + -------------------------------------------------------------------------------- + #
reward:
  # 초기화 되는 시간 (8시 일 경우 / hour: 8 minute: 0) 이렇게 입력 해주세요.
  # 기본 값은 오전 12시(am.12)로 설정되어 있습니다.
  # 0 ~ 23까지 입니다.
  # hour: 시간
  # minute: 분
  hour: 0
  minute: 0

  # 보상 시간 이름 설정
  time_name:
    REWARD_30M: '30분'
    REWARD_1H: '1시간'
    REWARD_2H: '2시간'
    REWARD_3H: '3시간'
    REWARD_6H: '6시간'
    REWARD_12H: '12시간'
    REWARD_15H: '15시간'

  # 보상 GUI 설정
  gui:
    # 보상을 받을 수 있을 때 아이템 설정 (줄바꿈은 "\n"으로 가능합니다.)
    canReward:
      # 아이템 종류 (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
      material: ENDER_CHEST
      # 아이템 이름
      # {time}: 위에 지정된 보상 시간 이름 설정 이름입니다.
      displayname: '&6[보상] {time}'
      # 아이템 로어
      lore: '\n &a클릭시 보상을 지급 받습니다.'

    # 보상을 받을 수 없을 때 아이템 설정 (줄바꿈은 "\n"으로 가능합니다.)
    cantReward:
      # 아이템 종류 (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
      material: BARRIER
      # 아이템 이름
      # {time}: 위에 지정된 보상 시간 이름 설정 이름입니다.
      displayname: '&6[보상] {time}'
      # 아이템 로어
      # 남은시간: {time}
      lore: '\n &c아직 보상을 받을 수 없습니다. \n &6[남은시간] : {time}'

    # 이미 보상을 받았을 때 아이템 설정 (줄바꿈은 "\n"으로 가능합니다.)
    receivedReward:
      # 아이템 종류 (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
      material: CHEST
      # 아이템 이름
      # {time}: 위에 지정된 보상 시간 이름 설정 이름입니다.
      displayname: '&6[보상] {time}'
      # 아이템 로어
      # 남은시간: {time}
      lore: '\n &c이미 보상을 지급 받았습니다.'


# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# + -------------------------------------------------------------------------------- + #
messages:
  # (메시지 앞에 붙는) 접두사
  prefix: ' &6접속보상 | &r'

  # 콘피그를 리로드 하였을 때 출력되는 메시지
  reloadComplete: '&a콘피그를 리로드하였습니다.'

  # 보상을 받았을 때 출력되는 메시지
  receiveReward: '&a접속시간 보상을 지급 받았습니다.'

  # 접속보상이 초기화 되었을 때 출력되는 메시지
  dailyResetMessage: '&a접속보상이 초기화 되었습니다. [/접속보상]'


errorMessages:
  # 권한이 없을 때 출력되는 메시지
  notAnOperator: '&c해당 명령어를 실행할 권한이 없습니다.'

  # 콘솔에서 불가능 명령어를 사용하였을 때 출력되는 메시지
  noConsoleCommand: '&c콘솔에서는 불가능한 명령어입니다. (인게임에서 시도해주세요)'

  # 잘못된 명령어를 사용하였을 때 출력되는 메시지
  wrongCommand: '&c잘못된 명령어입니다. (다시 시도해주세요)'

  # 올바르지 않은 REWARD TYPE일 경우 출력되는 메시지
  wrongRewardType: '&c올바르지 않은 보상 종류 입니다.'

  # 보상을 받는 도중 sql에 문제가 발생했을 경우 출력되는 메시지
  rewardSQLException: '&c보상을 받는 도중 오류가 발생하였습니다 (관리자에게 문의해주세요)'

  # 이미 보상을 받았을 때 출력되는 메시지
  alreadyRewardReceived: '&c이미 해당 접속시간 보상을 받으셨습니다.'

  # 인벤토리 공간이 충분하지 않아 보상읋 받지 못했을 경우 출력되는 메시지
  hasEnoughInventorySpace: '&c인벤토리 공간이 부족하여 보상을 받지 못하였습니다.'

  # 보상을 받기에 접속시간이 충분하지 않을 경우 출력되는 메시지
  # {time}: 남은시간
  InsufficientPlaytimeReward: '&c접속시간이 부족하여 아직 보상을 받을 수 없습니다. (남은시간: {time})'
