name: R-joinreward
main: net.starly.joinreward.JoinReward
author: Starly Team
website: http://starly.kr/

description: JoinReward Plugin.

depend: [ ST-Core ]

version: 1.0
api-version: 1.19

permissions:
  starly.joinreward.reload:
    description: 리로드 명령어
    default: op
  starly.joinreward.set:
    description: 접속보상 설정 명령어
    default: op
  starly.joinreward.*:
    description: R-joinreward 명령어에 대한 모든 권한
    children:
      - starly.joinreward.reload
      - starly.joinreward.set

commands:
  접속보상: